package com.nhl.link.move.writer;

import org.apache.cayenne.DataObject;
import org.apache.cayenne.ObjectId;
import org.apache.cayenne.map.DbAttribute;
import org.apache.cayenne.util.Util;

import com.nhl.link.move.LmRuntimeException;

/**
 * @since 1.4
 */
public class TargetPkPropertyWriter implements TargetPropertyWriter {

	private DbAttribute pk;

	public TargetPkPropertyWriter(DbAttribute pk) {

		if (!pk.isPrimaryKey()) {
			throw new LmRuntimeException("'" + pk.getName() + "' is not a PK");
		}

		this.pk = pk;

	}

	@Override
	public boolean write(DataObject target, Object value) {

		ObjectId id = target.getObjectId();

		if (Util.nullSafeEquals(id.getIdSnapshot().get(pk.getName()), value)) {
			return false;
		}

		if (Util.nullSafeEquals(id.getReplacementIdMap().get(pk.getName()), value)) {
			return false;
		}

		// PK is auto-generated ... This is sorta expected to fail -
		// generated meaningless PK should not be pushed from the client

		if (pk.isGenerated()) {
			throw new LmRuntimeException("'" + pk.getName()
					+ "' is autogenerated and is not allowed to be synced from source.");
		}

		// regular meaningless PK
		target.getObjectId().getReplacementIdMap().put(pk.getName(), value);

		return true;
	}
}
