package com.nhl.link.move.writer;

import com.nhl.link.move.LmRuntimeException;
import org.apache.cayenne.DataObject;
import org.apache.cayenne.map.DbAttribute;
import org.apache.cayenne.util.Util;

import java.util.Map;

/**
 * @since 1.4
 */
public class TargetPkPropertyWriter implements TargetPropertyWriter {

	private DbAttribute pk;

	public TargetPkPropertyWriter(DbAttribute pk) {

		if (!pk.isPrimaryKey()) {
			throw new LmRuntimeException("'" + pk.getName() + "' is not a PK");
		}

		this.pk = pk;

	}

	@Override
	public void write(DataObject target, Object value) {
		// regular meaningless PK
		target.getObjectId().getReplacementIdMap().put(pk.getName(), value);
	}

	@Override
	public boolean willWrite(DataObject target, Object value) {

		Map<String, Object> idSnapshot = target.getObjectId().getIdSnapshot();
		if (Util.nullSafeEquals(idSnapshot.get(pk.getName()), value)) {
			return false;
		}

		Map<String, Object> replacementMap = target.getObjectId().getReplacementIdMap();
		if (Util.nullSafeEquals(replacementMap.get(pk.getName()), value)) {
			return false;
		}

		if (pk.isGenerated()) {
			throw new LmRuntimeException("'" + pk.getName()
					+ "' is autogenerated and is not allowed to be synced from source.");
		}
		return true;
	}
}
