package com.nhl.link.move.runtime.task.delete;

import com.nhl.link.move.Execution;
import com.nhl.link.move.ExecutionStats;
import com.nhl.link.move.annotation.AfterMissingTargetsFiltered;
import com.nhl.link.move.annotation.AfterTargetsExtracted;

/**
 * A listener that collects task stats and stores them in the Execution's
 * {@link ExecutionStats} object.
 * 
 * @since 1.3
 */
public class DeleteStatsListener {
	private static final DeleteStatsListener instance = new DeleteStatsListener();

	public static DeleteStatsListener instance() {
		return instance;
	}

	@AfterTargetsExtracted
	public void targetsExtracted(Execution e, DeleteSegment<?> segment) {

	}

	// Not listening too @AfterSourceKeysExtracted
	// Extractor stats will be generated by the child SourceKeysTask

	@AfterMissingTargetsFiltered
	public void missedTargetsFound(Execution e, DeleteSegment<?> segment) {
		e.getStats().incrementDeleted(segment.getMissingTargets().height());
	}
}
