package com.nhl.link.move.unit.cayenne.t.auto;

import java.math.BigDecimal;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Etl8t was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Etl8t extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String C_DECIMAL1_PROPERTY = "cDecimal1";
    @Deprecated
    public static final String C_DECIMAL2_PROPERTY = "cDecimal2";
    @Deprecated
    public static final String C_DECIMAL3_PROPERTY = "cDecimal3";

    public static final String ID_PK_COLUMN = "id";

    public static final Property<BigDecimal> C_DECIMAL1 = new Property<BigDecimal>("cDecimal1");
    public static final Property<BigDecimal> C_DECIMAL2 = new Property<BigDecimal>("cDecimal2");
    public static final Property<BigDecimal> C_DECIMAL3 = new Property<BigDecimal>("cDecimal3");

    public void setCDecimal1(BigDecimal cDecimal1) {
        writeProperty("cDecimal1", cDecimal1);
    }
    public BigDecimal getCDecimal1() {
        return (BigDecimal)readProperty("cDecimal1");
    }

    public void setCDecimal2(BigDecimal cDecimal2) {
        writeProperty("cDecimal2", cDecimal2);
    }
    public BigDecimal getCDecimal2() {
        return (BigDecimal)readProperty("cDecimal2");
    }

    public void setCDecimal3(BigDecimal cDecimal3) {
        writeProperty("cDecimal3", cDecimal3);
    }
    public BigDecimal getCDecimal3() {
        return (BigDecimal)readProperty("cDecimal3");
    }

}
