package com.nhl.link.move.unit.cayenne.t.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Etl7t was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Etl7t extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> FIRST_NAME = new Property<String>("firstName");
    public static final Property<String> LAST_NAME = new Property<String>("lastName");
    public static final Property<String> SEX = new Property<String>("sex");

    public void setFirstName(String firstName) {
        writeProperty("firstName", firstName);
    }
    public String getFirstName() {
        return (String)readProperty("firstName");
    }

    public void setLastName(String lastName) {
        writeProperty("lastName", lastName);
    }
    public String getLastName() {
        return (String)readProperty("lastName");
    }

    public void setSex(String sex) {
        writeProperty("sex", sex);
    }
    public String getSex() {
        return (String)readProperty("sex");
    }

}
