package com.nhl.link.move.unit.cayenne.t.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _Etl11t was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Etl11t extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<byte[]> BIN = Property.create("bin", byte[].class);

    public void setBin(byte[] bin) {
        writeProperty("bin", bin);
    }
    public byte[] getBin() {
        return (byte[])readProperty("bin");
    }

}
