package com.nhl.link.move.unit.cayenne.t.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.nhl.link.move.unit.cayenne.t.Etl2t;
import com.nhl.link.move.unit.cayenne.t.Etl5t;

/**
 * Class _Etl3t was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Etl3t extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<String> PHONE_NUMBER = Property.create("phoneNumber", String.class);
    public static final Property<Etl2t> E2 = Property.create("e2", Etl2t.class);
    public static final Property<Etl5t> E5 = Property.create("e5", Etl5t.class);

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPhoneNumber(String phoneNumber) {
        writeProperty("phoneNumber", phoneNumber);
    }
    public String getPhoneNumber() {
        return (String)readProperty("phoneNumber");
    }

    public void setE2(Etl2t e2) {
        setToOneTarget("e2", e2, true);
    }

    public Etl2t getE2() {
        return (Etl2t)readProperty("e2");
    }


    public void setE5(Etl5t e5) {
        setToOneTarget("e5", e5, true);
    }

    public Etl5t getE5() {
        return (Etl5t)readProperty("e5");
    }


}
