package com.nhl.link.move.unit.cayenne.t.auto;

import java.util.Date;
import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.nhl.link.move.unit.cayenne.t.Etl3t;

/**
 * Class _Etl5t was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Etl5t extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Date> DATE = new Property<Date>("date");
    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<List<Etl3t>> E2S = new Property<List<Etl3t>>("e2s");

    public void setDate(Date date) {
        writeProperty("date", date);
    }
    public Date getDate() {
        return (Date)readProperty("date");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToE2s(Etl3t obj) {
        addToManyTarget("e2s", obj, true);
    }
    public void removeFromE2s(Etl3t obj) {
        removeToManyTarget("e2s", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<Etl3t> getE2s() {
        return (List<Etl3t>)readProperty("e2s");
    }


}
