CREATE TABLE "etlt1" ("id" BIGINT  NOT NULL, "num_int" INTEGER , "string" VARCHAR (100), PRIMARY KEY ("id"))
;

CREATE SEQUENCE "PK_ETLT1" AS BIGINT START WITH 200 INCREMENT BY 20 NO MAXVALUE NO CYCLE
;
