package com.nhl.link.move.runtime.json.query;

enum TokenType {
    ROOT_NODE_REF, CURRENT_NODE_REF, CHILD_ACCESS, RECURSIVE_DESCENT, WILDCARD, UNION,
    FILTER_START, FILTER_END, PREDICATE_START, SCRIPT_START, SCRIPT_END,
    IDENTIFIER, QUOTED_IDENTIFIER, NUMERIC_VALUE
}
