package com.nhl.link.move.unit.cayenne.ti.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _TiSuper was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TiSuper extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> SUPER_KEY = Property.create("superKey", String.class);
    public static final Property<String> TYPE = Property.create("type", String.class);

    public void setSuperKey(String superKey) {
        writeProperty("superKey", superKey);
    }
    public String getSuperKey() {
        return (String)readProperty("superKey");
    }

    public void setType(String type) {
        writeProperty("type", type);
    }
    public String getType() {
        return (String)readProperty("type");
    }

}
