package com.nhl.link.move.unit.cayenne.ti.auto;

import org.apache.cayenne.exp.Property;

import com.nhl.link.move.unit.cayenne.ti.TiSuper;

/**
 * Class _TiSub1 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TiSub1 extends TiSuper {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> SUB_KEY = Property.create("subKey", String.class);
    public static final Property<String> SUBP1 = Property.create("subp1", String.class);

    public void setSubKey(String subKey) {
        writeProperty("subKey", subKey);
    }
    public String getSubKey() {
        return (String)readProperty("subKey");
    }

    public void setSubp1(String subp1) {
        writeProperty("subp1", subp1);
    }
    public String getSubp1() {
        return (String)readProperty("subp1");
    }

}
