package com.nhl.link.move.model.cayenne.auto;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _TestTime was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _TestTime extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<LocalDate> LOCAL_DATE = Property.create("localDate", LocalDate.class);
    public static final Property<LocalDateTime> LOCAL_DATE_TIME = Property.create("localDateTime", LocalDateTime.class);
    public static final Property<LocalTime> LOCAL_TIME = Property.create("localTime", LocalTime.class);

    public void setLocalDate(LocalDate localDate) {
        writeProperty("localDate", localDate);
    }
    public LocalDate getLocalDate() {
        return (LocalDate)readProperty("localDate");
    }

    public void setLocalDateTime(LocalDateTime localDateTime) {
        writeProperty("localDateTime", localDateTime);
    }
    public LocalDateTime getLocalDateTime() {
        return (LocalDateTime)readProperty("localDateTime");
    }

    public void setLocalTime(LocalTime localTime) {
        writeProperty("localTime", localTime);
    }
    public LocalTime getLocalTime() {
        return (LocalTime)readProperty("localTime");
    }

}
